package com.example.dermtect.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import com.example.dermtect.R

@Composable
fun AboutScreen(navController: NavController) {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0xFFF5F5F5)) // fallback background
    ) {
        // Cyan background rectangle
        Box(
            modifier = Modifier
                .offset(y = 59.dp)
                .fillMaxWidth()
                .height(833.dp)
                .clip(RoundedCornerShape(20.dp))
                .background(Color(0xFFCDFFFF))
        )

        // Back button slightly above the About title
        Box(
            modifier = Modifier
                .padding(start = 20.dp, top = 68.dp)
                .size(37.dp)
                .clip(CircleShape)
                .background(Color.White)
                .clickable { navController.popBackStack() },
            contentAlignment = Alignment.Center
        ) {
            Icon(
                painter = painterResource(id = R.drawable.back),
                contentDescription = "Back"
            )
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(top = 100.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // About title (not bold)
            Text(
                text = "About",
                fontSize = 24.sp,
                color = Color(0xFF1D1D1D),
                fontWeight = androidx.compose.ui.text.font.FontWeight.Normal
            )

            Spacer(modifier = Modifier.height(16.dp))

            // White content card centered
            Card(
                modifier = Modifier
                    .width(363.dp)
                    .height(706.dp),
                shape = RoundedCornerShape(10.dp),
                colors = CardDefaults.cardColors(containerColor = Color.White)
            ) {
                Column(
                    modifier = Modifier
                        .padding(20.dp)
                        .verticalScroll(rememberScrollState()),
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    Text(
                        text = """
DermTect is a mobile app designed to help people check their skin for early signs of skin cancer. It works by allowing users to take a clear photo of a mole, spot, or unusual mark on their skin using their phone’s camera. Once the photo is taken, the app analyzes the image and lets the user know if the skin spot looks like it could be cancerous or not.

The goal of DermTect is not to replace a doctor, but to give users an easy way to monitor their skin health, especially if they notice something new or unusual. By providing quick feedback, the app encourages users to be more aware of changes in their skin and to seek medical advice from a dermatologist if anything seems suspicious.

Early detection can make a big difference, and DermTect aims to make that first step simple and accessible for everyone.

Credits:
International Skin Imaging Collaboration. SLICE-3D 2024 Challenge Dataset. International Skin Imaging Collaboration https://doi.org/10.34970/2024-slice-3d

The dataset was generated by the International Skin Imaging Collaboration (ISIC) and images are from the following sources: Hospital Clínic de Barcelona, Memorial Sloan Kettering Cancer Center, Hospital of Basel, FNQH Cairns, The University of Queensland, Melanoma Institute Australia, Monash University and Alfred Health, University of Athens Medical School, and Medical University of Vienna.
""".trimIndent(),
                        fontSize = 14.sp,
                        color = Color(0xFF484848),
                        lineHeight = 20.sp,
                        textAlign = TextAlign.Center,
                        fontWeight = androidx.compose.ui.text.font.FontWeight.Normal
                    )
                }
            }
        }
    }
}
